// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Error": {
    "description": "<p>We've unfortunately encountered an error.</p><p>You can try to <retry>reload the page</retry> you were visiting.</p>",
    "title": "Something went wrong!"
  },
  "IndexPage": {
    "description": "This is a basic example that demonstrates the usage of <code>next-intl</code> with the Next.js App Router. Try changing the locale in the top right corner and see how the content changes.",
    "title": "next-intl example"
  },
  "LocaleLayout": {
    "title": "next-intl example"
  },
  "LocaleSwitcher": {
    "label": "Change language",
    "locale": "{locale, select, vi {VietNam} en {English} other {Unknown}}"
  },
  "Manifest": {
    "name": "next-intl example"
  },
  "Navigation": {
    "home": "Home",
    "pathnames": "Pathnames"
  },
  "NotFoundPage": {
    "description": "Please double-check the browser address bar or use the navigation to go to a known page.",
    "title": "Page not found"
  },
  "PageLayout": {
    "links": {
      "docs": {
        "description": "Learn more about next-intl in the official docs.",
        "href": "https://next-intl.dev",
        "title": "Docs"
      },
      "source": {
        "description": "Browse the source code of this example on GitHub.",
        "href": "https://github.com/amannn/next-intl/tree/main/examples/example-app-router",
        "title": "Source code"
      }
    }
  },
  "PathnamesPage": {
    "description": "<p>The pathnames are internationalized too.</p><p>If you're using the default language English, you'll see <code>/en/pathnames</code> in the browser address bar on this page.</p><p>If you change the locale to German, the URL is localized accordingly (<code>/de/pfadnamen</code>).</p>",
    "title": "Pathnames"
  },
  "sidebar": {
    "items": {
      "dashboard": "Dashboard",
      "sample": "Sample",
      "components": "Components",
      "login": "Login",
      "register": "Register",
      "error404": "Error 404",
      "error500": "Error 500",
      "docs": "Docs",
      "try_core_ui_pro": "Try CoreUI PRO",
      "base": "Base",
      "forms": "Forms",
      "icons": "Icons",
      "notifications": "Notifications",
      "extras": "Extras",
      "pages": "Pages",
      "ecommerce": "Ecommerce",
      "reports" : "Reports",
      "orders" : "Orders",
      "products" : "Products",
      "products_categories" : "Products Categories",
      "products_tags" : "Products Tags",
      "products_atributes" : "Products Atributes",
      "products_collections" : "Products Collections",
      "products_labels" : "Products labels",
      "reviews" : "Reviews",
      "discounts" : "Discounts",
      "customers" : "Customers",
      "blog" : "Blog",
      "posts" : "Posts",
      "blog_categories" : "Blog Categories",
      "blog_tag" : "Blog Tags",
      "payments" : "Payments",
      "contact" : "Contact",
      "faqs" :" FAQs",
      "faqs_categories" :" FAQs Categories",
      "media" : "Media",
      "settings" : "Setting",
      "admin" : "Admin"
    }
  }
};
export default messages;